pipeline {
    agent any
    stages {
        stage('Hello') {
            steps {
                git branch:'main', credentialsId:'github-token', url:'https://github.com/s87k/test_jenkins2.git'
            }
        }
    }
}