pipeline {
    agent any
    tools {
        maven 'Maven' // Jenkins tools에 설정한 Maven의 이름
    }

    environment {
        JAVA_HOME='C:\\dev\\java-11-openjdk-11.0.15.9-1'    // 자바가 설치된 경로
        PATH="${env.JAVA_HOME}\\bin;${env.PATH}"
    }

    trigger {
        pollSCM('H/6 * * * 1-5')
    }

    stages {
        stage('clone repository') {
            steps {
                git branch:'main', credentialsId:'github-token', url:'https://github.com/s87k/test_jenkins2.git'
            }
        }

        stage('buile WAR'){
            steps{
                script{
                    def mvnHome = tool name: 'Maven', type:'hudson.tasks.Maven$MavenInstallation'   // Maven: Jenkins의 tools에 설정한 maven 이름
                    withEnv(["MAVEN_HOME=${mvnHome}"]) {
                        // pom.xml의 version 노드의 이름으로 war가 targit 디렉토리에 생성된다
                        bat "\"${mvnHome}\\bin\\mvn\" clean package-DskipTests"
                    }
                }
            }
        }

    }
}